CC=gcc
CCFLAGS=-g3 -Wall -Wextra -O3 -DUSE_DL_PREFIX -DREALLOC_ZERO_BYTES_FREE -DUSE_LOCKS -Daqilla -rdynamic
#TEST_CCFLAGS=-g3 -Wall -Wextra -DUSE_DL_PREFIX -DREALLOC_ZERO_BYTES_FREE -DUSE_LOCKS -D_DEBUG_ON -Daqilla -D_test_suite -D_UNDER_DEV
TEST_CCFLAGS=-g3

deb:
	cp libsafeheap.so ./debian/safeheap/usr/lib/
	cp run-with-safeheap.sh ./debian/safeheap/usr/sbin/

install:
	cp libsafeheap.so /usr/lib/
	cp run-with-safeheap.sh /usr/sbin/ 	
clean:
	rm libsafeheap.so tcp* tcc* tcw*
tar:
	tar zcvf safeheap.tar.gz malloc.c safeheap.c test Makefile run-with-safeheap.sh run-tests.sh
safeheap:
	$(CC) $(CCFLAGS) malloc.c safeheap.c -shared -fPIC -o libsafeheap.so -ldl -lpthread
	
build:
	$(CC) $(CCFLAGS) malloc.c safeheap.c -shared -fPIC -o libsafeheap.so -ldl -lpthread
	$(CC) $(TEST_CCFLAGS) test/tcp1.c -o tcp1
	$(CC) $(TEST_CCFLAGS) test/tcp2.c -o tcp2
	$(CC) $(TEST_CCFLAGS) test/tcp3.c -o tcp3
	$(CC) $(TEST_CCFLAGS) test/tcp4.c -o tcp4
	$(CC) $(TEST_CCFLAGS) test/tcp5.c -o tcp5
	$(CC) $(TEST_CCFLAGS) test/tcp6.c -o tcp6
	$(CC) $(TEST_CCFLAGS) test/tcp7.c -o tcp7
	$(CC) $(TEST_CCFLAGS) test/tcp8.c -o tcp8
	$(CC) $(TEST_CCFLAGS) test/tcp9.c -o tcp9
	$(CC) $(TEST_CCFLAGS) test/tcp10.c -o tcp10
	$(CC) $(TEST_CCFLAGS) test/tcp11.c -o tcp11
	$(CC) $(TEST_CCFLAGS) test/tcp12.c -o tcp12
	$(CC) $(TEST_CCFLAGS) test/tcp13.c -o tcp13
	$(CC) $(TEST_CCFLAGS) test/tcp14.c -o tcp14
	$(CC) $(TEST_CCFLAGS) test/tcp15.c -o tcp15
	$(CC) $(TEST_CCFLAGS) test/tcp16.c -o tcp16
	$(CC) $(TEST_CCFLAGS) test/tcp17.c -o tcp17
	$(CC) $(TEST_CCFLAGS) test/tcp18.c -o tcp18
	$(CC) $(TEST_CCFLAGS) test/tcp19.c -o tcp19
	$(CC) $(TEST_CCFLAGS) test/tcp20.c -o tcp20
	$(CC) $(TEST_CCFLAGS) test/tcp21.c -o tcp21
	$(CC) $(TEST_CCFLAGS) test/tcp22.c -o tcp22
	$(CC) $(TEST_CCFLAGS) test/tcp23.c -o tcp23
	$(CC) $(TEST_CCFLAGS) test/tcp24.c -o tcp24
	$(CC) $(TEST_CCFLAGS) test/tcp25.c -o tcp25
	$(CC) $(TEST_CCFLAGS) test/tcp26.c -o tcp26
	$(CC) $(TEST_CCFLAGS) test/tcp27.c -o tcp27
	$(CC) $(TEST_CCFLAGS) test/tcp28.c -o tcp28
	$(CC) $(TEST_CCFLAGS) test/tcp29.c -o tcp29
	$(CC) $(TEST_CCFLAGS) test/tcp30.c -o tcp30
	$(CC) $(TEST_CCFLAGS) test/tcp31.c -o tcp31
	$(CC) $(TEST_CCFLAGS) test/tcp32.c -o tcp32
	$(CC) $(TEST_CCFLAGS) test/tcp33.c -o tcp33
	$(CC) $(TEST_CCFLAGS) test/tcp34.c -o tcp34
	$(CC) $(TEST_CCFLAGS) test/tcp35.c -o tcp35
	$(CC) $(TEST_CCFLAGS) test/tcp36.c -o tcp36
	$(CC) $(TEST_CCFLAGS) test/tcp51.c -o tcp51
	$(CC) $(TEST_CCFLAGS) test/tcp51.c -o tcp52
	$(CC) $(TEST_CCFLAGS) test/tcp53.c -o tcp53
	$(CC) $(TEST_CCFLAGS) test/tcp54.c -o tcp54
	$(CC) $(TEST_CCFLAGS) test/tcp55.c -o tcp55
	$(CC) $(TEST_CCFLAGS) test/tcp56.c -o tcp56
	$(CC) $(TEST_CCFLAGS) test/tcp57.c -o tcp57
	$(CC) $(TEST_CCFLAGS) test/tcp58.c -o tcp58
	$(CC) $(TEST_CCFLAGS) test/tcp59.c -o tcp59
	$(CC) $(TEST_CCFLAGS) test/tcp60.c -o tcp60
	$(CC) $(TEST_CCFLAGS) test/tcp61.c -o tcp61
	$(CC) $(TEST_CCFLAGS) test/tcp62.c -o tcp62
	$(CC) $(TEST_CCFLAGS) test/tcp63.c -o tcp63
	$(CC) $(TEST_CCFLAGS) test/tcp64.c -o tcp64
	$(CC) $(TEST_CCFLAGS) test/tcp65.c -o tcp65
	$(CC) $(TEST_CCFLAGS) test/tcp66.c -o tcp66
	$(CC) $(TEST_CCFLAGS) test/tcp67.c -o tcp67
	$(CC) $(TEST_CCFLAGS) test/tcp68.c -o tcp68
	$(CC) $(TEST_CCFLAGS) test/tcp69.c -o tcp69
	$(CC) $(TEST_CCFLAGS) test/tcp70.c -o tcp70
	$(CC) $(TEST_CCFLAGS) test/tcp71.c -o tcp71
	$(CC) $(TEST_CCFLAGS) test/tcp72.c -o tcp72
	$(CC) $(TEST_CCFLAGS) test/tcp73.c -o tcp73
	$(CC) $(TEST_CCFLAGS) test/tcp74.c -o tcp74
	$(CC) $(TEST_CCFLAGS) test/tcp75.c -o tcp75
	$(CC) $(TEST_CCFLAGS) test/tcp76.c -o tcp76
	$(CC) $(TEST_CCFLAGS) test/tcp77.c -o tcp77
	$(CC) $(TEST_CCFLAGS) test/tcp78.c -o tcp78
	$(CC) $(TEST_CCFLAGS) test/tcp79.c -o tcp79
	$(CC) $(TEST_CCFLAGS) test/tcp80.c -o tcp80
	$(CC) $(TEST_CCFLAGS) test/tcp81.c -o tcp81
	$(CC) $(TEST_CCFLAGS) test/tcp82.c -o tcp82
	$(CC) $(TEST_CCFLAGS) test/tcp83.c -o tcp83
	$(CC) $(TEST_CCFLAGS) test/tcp84.c -o tcp84
	$(CC) $(TEST_CCFLAGS) test/tcpth1.c -o tcpth1 -lpthread
	$(CC) $(TEST_CCFLAGS) test/tcc1.c -o tcc1
	$(CC) $(TEST_CCFLAGS) test/tcc2.c -o tcc2
	$(CC) $(TEST_CCFLAGS) test/tcc3.c -o tcc3
	$(CC) $(TEST_CCFLAGS) test/tcc4.c -o tcc4
	$(CC) $(TEST_CCFLAGS) test/tcc5.c -o tcc5
	$(CC) $(TEST_CCFLAGS) test/tcc6.c -o tcc6
	$(CC) $(TEST_CCFLAGS) test/tcc7.c -o tcc7
	$(CC) $(TEST_CCFLAGS) test/tcc8.c -o tcc8
	$(CC) $(TEST_CCFLAGS) test/tcc9.c -o tcc9
	$(CC) $(TEST_CCFLAGS) test/tcc10.c -o tcc10
	$(CC) $(TEST_CCFLAGS) test/tcc11.c -o tcc11
	$(CC) $(TEST_CCFLAGS) test/tcc12.c -o tcc12
	$(CC) $(TEST_CCFLAGS) test/tcc13.c -o tcc13
	$(CC) $(TEST_CCFLAGS) test/tcc14.c -o tcc14
	$(CC) $(TEST_CCFLAGS) test/tcc15.c -o tcc15
	$(CC) $(TEST_CCFLAGS) test/tcc16.c -o tcc16
	$(CC) $(TEST_CCFLAGS) test/tcc17.c -o tcc17
	$(CC) $(TEST_CCFLAGS) test/tcc18.c -o tcc18
	$(CC) $(TEST_CCFLAGS) test/tcc19.c -o tcc19
	$(CC) $(TEST_CCFLAGS) test/tcc20.c -o tcc20
	$(CC) $(TEST_CCFLAGS) test/tcc21.c -o tcc21
	$(CC) $(TEST_CCFLAGS) test/tcc22.c -o tcc22
	$(CC) $(TEST_CCFLAGS) test/tcc23.c -o tcc23
	$(CC) $(TEST_CCFLAGS) test/tcc24.c -o tcc24
	$(CC) $(TEST_CCFLAGS) test/tcc25.c -o tcc25
	$(CC) $(TEST_CCFLAGS) test/tcc26.c -o tcc26
	$(CC) $(TEST_CCFLAGS) test/tcc27.c -o tcc27
	$(CC) $(TEST_CCFLAGS) test/tcc28.c -o tcc28
	$(CC) $(TEST_CCFLAGS) test/tcc29.c -o tcc29
	$(CC) $(TEST_CCFLAGS) test/tcc30.c -o tcc30
	$(CC) $(TEST_CCFLAGS) test/tcc31.c -o tcc31
	$(CC) $(TEST_CCFLAGS) test/tcc32.c -o tcc32
	$(CC) $(TEST_CCFLAGS) test/tcc33.c -o tcc33
	$(CC) $(TEST_CCFLAGS) test/tcc34.c -o tcc34
	$(CC) $(TEST_CCFLAGS) test/tcc35.c -o tcc35
	$(CC) $(TEST_CCFLAGS) test/tcc36.c -o tcc36
	$(CC) $(TEST_CCFLAGS) test/tcc37.c -o tcc37
	$(CC) $(TEST_CCFLAGS) test/tcc38.c -o tcc38
	$(CC) $(TEST_CCFLAGS) test/tcc39.c -o tcc39
	$(CC) $(TEST_CCFLAGS) test/tcc40.c -o tcc40
	$(CC) $(TEST_CCFLAGS) test/tcc41.c -o tcc41
	$(CC) $(TEST_CCFLAGS) test/tcc42.c -o tcc42
	$(CC) $(TEST_CCFLAGS) test/tcc43.c -o tcc43
	$(CC) $(TEST_CCFLAGS) test/tcc44.c -o tcc44
	$(CC) $(TEST_CCFLAGS) test/tcc45.c -o tcc45
	$(CC) $(TEST_CCFLAGS) test/tcc46.c -o tcc46
	$(CC) $(TEST_CCFLAGS) test/tcc47.c -o tcc47
	$(CC) $(TEST_CCFLAGS) test/tcc48.c -o tcc48
	$(CC) $(TEST_CCFLAGS) test/tcc49.c -o tcc49
	$(CC) $(TEST_CCFLAGS) test/tcc50.c -o tcc50
	$(CC) $(TEST_CCFLAGS) test/tcc51.c -o tcc51
	$(CC) $(TEST_CCFLAGS) test/tcc52.c -o tcc52
	$(CC) $(TEST_CCFLAGS) test/tcc53.c -o tcc53
	$(CC) $(TEST_CCFLAGS) test/tcc54.c -o tcc54
	$(CC) $(TEST_CCFLAGS) test/tcc55.c -o tcc55
	$(CC) $(TEST_CCFLAGS) test/tcc56.c -o tcc56
	$(CC) $(TEST_CCFLAGS) test/tcc57.c -o tcc57
	$(CC) $(TEST_CCFLAGS) test/tcc58.c -o tcc58
	$(CC) $(TEST_CCFLAGS) test/tcc59.c -o tcc59
	$(CC) $(TEST_CCFLAGS) test/tcc60.c -o tcc60
	$(CC) $(TEST_CCFLAGS) test/tcc61.c -o tcc61
	$(CC) $(TEST_CCFLAGS) test/tcc62.c -o tcc62
	$(CC) $(TEST_CCFLAGS) test/tcc63.c -o tcc63
	$(CC) $(TEST_CCFLAGS) test/tcc64.c -o tcc64
	$(CC) $(TEST_CCFLAGS) test/tcc65.c -o tcc65
	$(CC) $(TEST_CCFLAGS) test/tcc66.c -o tcc66
	$(CC) $(TEST_CCFLAGS) test/tcc67.c -o tcc67
	$(CC) $(TEST_CCFLAGS) test/tcc68.c -o tcc68
	$(CC) $(TEST_CCFLAGS) test/tcc69.c -o tcc69
	$(CC) $(TEST_CCFLAGS) test/tcc70.c -o tcc70
	$(CC) $(TEST_CCFLAGS) test/tcc71.c -o tcc71
	$(CC) $(TEST_CCFLAGS) test/tcc72.c -o tcc72
	$(CC) $(TEST_CCFLAGS) test/tcc73.c -o tcc73
	$(CC) $(TEST_CCFLAGS) test/tcc74.c -o tcc74
	$(CC) $(TEST_CCFLAGS) test/tcc75.c -o tcc75
	$(CC) $(TEST_CCFLAGS) test/tcc76.c -o tcc76
	$(CC) $(TEST_CCFLAGS) test/tcc77.c -o tcc77
	$(CC) $(TEST_CCFLAGS) test/tcc78.c -o tcc78
	$(CC) $(TEST_CCFLAGS) test/tcc79.c -o tcc79
	$(CC) $(TEST_CCFLAGS) test/tcc80.c -o tcc80
	$(CC) $(TEST_CCFLAGS) test/tcc81.c -o tcc81
	$(CC) $(TEST_CCFLAGS) test/tcc82.c -o tcc82
	$(CC) $(TEST_CCFLAGS) test/tcc83.c -o tcc83
	$(CC) $(TEST_CCFLAGS) test/tcc84.c -o tcc84
	$(CC) $(TEST_CCFLAGS) test/tcc85.c -o tcc85
	$(CC) $(TEST_CCFLAGS) test/tcc86.c -o tcc86
	$(CC) $(TEST_CCFLAGS) test/tcc87.c -o tcc87
	$(CC) $(TEST_CCFLAGS) test/tcc88.c -o tcc88
	$(CC) $(TEST_CCFLAGS) test/tcc89.c -o tcc89
	$(CC) $(TEST_CCFLAGS) test/tcc90.c -o tcc90
	$(CC) $(TEST_CCFLAGS) test/tcc91.c -o tcc91
	$(CC) $(TEST_CCFLAGS) test/tcc92.c -o tcc92
	$(CC) $(TEST_CCFLAGS) test/tcc93.c -o tcc93
	$(CC) $(TEST_CCFLAGS) test/tcc94.c -o tcc94
	$(CC) $(TEST_CCFLAGS) test/tcc95.c -o tcc95
	$(CC) $(TEST_CCFLAGS) test/tcc96.c -o tcc96
	$(CC) $(TEST_CCFLAGS) test/tcc97.c -o tcc97
	$(CC) $(TEST_CCFLAGS) test/tcc98.c -o tcc98
	$(CC) $(TEST_CCFLAGS) test/tcc99.c -o tcc99
	$(CC) $(TEST_CCFLAGS) test/tcc100.c -o tcc100
	$(CC) $(TEST_CCFLAGS) test/tcc101.c -o tcc101
	$(CC) $(TEST_CCFLAGS) test/tcc102.c -o tcc102
	$(CC) $(TEST_CCFLAGS) test/tcc103.c -o tcc103
	$(CC) $(TEST_CCFLAGS) test/tcc104.c -o tcc104
	$(CC) $(TEST_CCFLAGS) test/tcc105.c -o tcc105
	$(CC) $(TEST_CCFLAGS) test/tcc106.c -o tcc106
	$(CC) $(TEST_CCFLAGS) test/tcc107.c -o tcc107
	$(CC) $(TEST_CCFLAGS) test/tcc108.c -o tcc108
	$(CC) $(TEST_CCFLAGS) test/tcc109.c -o tcc109
	$(CC) $(TEST_CCFLAGS) test/tcc110.c -o tcc110
	$(CC) $(TEST_CCFLAGS) test/tcc111.c -o tcc111
	$(CC) $(TEST_CCFLAGS) test/tcc112.c -o tcc112
	$(CC) $(TEST_CCFLAGS) test/tcc113.c -o tcc113
	$(CC) $(TEST_CCFLAGS) test/tcc114.c -o tcc114
	$(CC) $(TEST_CCFLAGS) test/tcc115.c -o tcc115
	$(CC) $(TEST_CCFLAGS) test/tcc116.c -o tcc116
	$(CC) $(TEST_CCFLAGS) test/tcc117.c -o tcc117
	$(CC) $(TEST_CCFLAGS) test/tcc118.c -o tcc118
	$(CC) $(TEST_CCFLAGS) test/tcc119.c -o tcc119
	$(CC) $(TEST_CCFLAGS) test/tcc120.c -o tcc120
	$(CC) $(TEST_CCFLAGS) test/tcc121.c -o tcc121
	$(CC) $(TEST_CCFLAGS) test/tcc122.c -o tcc122
	$(CC) $(TEST_CCFLAGS) test/tcc123.c -o tcc123
	$(CC) $(TEST_CCFLAGS) test/tcc124.c -o tcc124
	$(CC) $(TEST_CCFLAGS) test/tcc125.c -o tcc125
	$(CC) $(TEST_CCFLAGS) test/tcc126.c -o tcc126
	$(CC) $(TEST_CCFLAGS) test/tcc127.c -o tcc127
	$(CC) $(TEST_CCFLAGS) test/tcc128.c -o tcc128
	$(CC) $(TEST_CCFLAGS) test/tcc129.c -o tcc129
	$(CC) $(TEST_CCFLAGS) test/tcc130.c -o tcc130
	$(CC) $(TEST_CCFLAGS) test/tcc131.c -o tcc131
	$(CC) $(TEST_CCFLAGS) test/tcc132.c -o tcc132
	$(CC) $(TEST_CCFLAGS) test/tcc133.c -o tcc133
	$(CC) $(TEST_CCFLAGS) test/tcc134.c -o tcc134
	$(CC) $(TEST_CCFLAGS) test/tcc135.c -o tcc135
	$(CC) $(TEST_CCFLAGS) test/tcc136.c -o tcc136
	$(CC) $(TEST_CCFLAGS) test/tcc137.c -o tcc137
	$(CC) $(TEST_CCFLAGS) test/tcc138.c -o tcc138
	$(CC) $(TEST_CCFLAGS) test/tcc139.c -o tcc139
	$(CC) $(TEST_CCFLAGS) test/tcc140.c -o tcc140
	$(CC) $(TEST_CCFLAGS) test/tcc141.c -o tcc141
	$(CC) $(TEST_CCFLAGS) test/tcc142.c -o tcc142
	$(CC) $(TEST_CCFLAGS) test/tcc143.c -o tcc143
	$(CC) $(TEST_CCFLAGS) test/tcc144.c -o tcc144
	$(CC) $(TEST_CCFLAGS) test/tcc145.c -o tcc145
	$(CC) $(TEST_CCFLAGS) test/tcc146.c -o tcc146
	$(CC) $(TEST_CCFLAGS) test/tcc147.c -o tcc147
	$(CC) $(TEST_CCFLAGS) test/tcc148.c -o tcc148
	$(CC) $(TEST_CCFLAGS) test/tcc149.c -o tcc149
	$(CC) $(TEST_CCFLAGS) test/tcc150.c -o tcc150
	$(CC) $(TEST_CCFLAGS) test/tcc151.c -o tcc151
	$(CC) $(TEST_CCFLAGS) test/tcc152.c -o tcc152
	$(CC) $(TEST_CCFLAGS) test/tcc153.c -o tcc153
	$(CC) $(TEST_CCFLAGS) test/tcc154.c -o tcc154
	$(CC) $(TEST_CCFLAGS) test/tcc155.c -o tcc155
	$(CC) $(TEST_CCFLAGS) test/tcc156.c -o tcc156
	$(CC) $(TEST_CCFLAGS) test/tcc157.c -o tcc157
	$(CC) $(TEST_CCFLAGS) test/tcc158.c -o tcc158
	$(CC) $(TEST_CCFLAGS) test/tcc159.c -o tcc159
	$(CC) $(TEST_CCFLAGS) test/tcc160.c -o tcc160
	$(CC) $(TEST_CCFLAGS) test/tcc161.c -o tcc161
	$(CC) $(TEST_CCFLAGS) test/tcc162.c -o tcc162
	$(CC) $(TEST_CCFLAGS) test/tcc163.c -o tcc163
	$(CC) $(TEST_CCFLAGS) test/tcc164.c -o tcc164
	$(CC) $(TEST_CCFLAGS) test/tcc165.c -o tcc165
	$(CC) $(TEST_CCFLAGS) test/tcc166.c -o tcc166
	$(CC) $(TEST_CCFLAGS) test/tcc167.c -o tcc167
	$(CC) $(TEST_CCFLAGS) test/tcc168.c -o tcc168
	$(CC) $(TEST_CCFLAGS) test/tcc169.c -o tcc169
	$(CC) $(TEST_CCFLAGS) test/tcc170.c -o tcc170
	$(CC) $(TEST_CCFLAGS) test/tcc171.c -o tcc171
	$(CC) $(TEST_CCFLAGS) test/tcc172.c -o tcc172
	$(CC) $(TEST_CCFLAGS) test/tcc173.c -o tcc173
	$(CC) $(TEST_CCFLAGS) test/tcc174.c -o tcc174
	$(CC) $(TEST_CCFLAGS) test/tcc175.c -o tcc175
	$(CC) $(TEST_CCFLAGS) test/tcc176.c -o tcc176
	$(CC) $(TEST_CCFLAGS) test/tcc177.c -o tcc177
	$(CC) $(TEST_CCFLAGS) test/tcc178.c -o tcc178
	$(CC) $(TEST_CCFLAGS) test/tcc179.c -o tcc179
	$(CC) $(TEST_CCFLAGS) test/tcc180.c -o tcc180
	$(CC) $(TEST_CCFLAGS) test/tcc181.c -o tcc181
	$(CC) $(TEST_CCFLAGS) test/tcc182.c -o tcc182
	$(CC) $(TEST_CCFLAGS) test/tcc183.c -o tcc183
	$(CC) $(TEST_CCFLAGS) test/tcc184.c -o tcc184
	$(CC) $(TEST_CCFLAGS) test/tcc185.c -o tcc185
	$(CC) $(TEST_CCFLAGS) test/tcc186.c -o tcc186
	$(CC) $(TEST_CCFLAGS) test/tcc187.c -o tcc187
	$(CC) $(TEST_CCFLAGS) test/tcc200.c -o tcc200
	$(CC) $(TEST_CCFLAGS) test/tcc201.c -o tcc201
	$(CC) $(TEST_CCFLAGS) test/tcc202.c -o tcc202
	$(CC) $(TEST_CCFLAGS) test/tcc203.c -o tcc203
	$(CC) $(TEST_CCFLAGS) test/tcc204.c -o tcc204
	$(CC) $(TEST_CCFLAGS) test/tcc205.c -o tcc205
	$(CC) $(TEST_CCFLAGS) test/tcc206.c -o tcc206
	$(CC) $(TEST_CCFLAGS) test/tcc207.c -o tcc207
	$(CC) $(TEST_CCFLAGS) test/tcc208.c -o tcc208
	$(CC) $(TEST_CCFLAGS) test/tcc209.c -o tcc209
	$(CC) $(TEST_CCFLAGS) test/tcc210.c -o tcc210
	$(CC) $(TEST_CCFLAGS) test/tcc211.c -o tcc211
	$(CC) $(TEST_CCFLAGS) test/tcc212.c -o tcc212
	$(CC) $(TEST_CCFLAGS) test/tcc213.c -o tcc213
	$(CC) $(TEST_CCFLAGS) test/tcc214.c -o tcc214
	$(CC) $(TEST_CCFLAGS) test/tcc215.c -o tcc215
	$(CC) $(TEST_CCFLAGS) test/tcc216.c -o tcc216
	$(CC) $(TEST_CCFLAGS) test/tcc217.c -o tcc217
	$(CC) $(TEST_CCFLAGS) test/tcc218.c -o tcc218
	$(CC) $(TEST_CCFLAGS) test/tcc219.c -o tcc219
	$(CC) $(TEST_CCFLAGS) test/tcc220.c -o tcc220
	$(CC) $(TEST_CCFLAGS) test/tcc221.c -o tcc221
	$(CC) $(TEST_CCFLAGS) test/tcc222.c -o tcc222
	$(CC) $(TEST_CCFLAGS) test/tcc223.c -o tcc223
	$(CC) $(TEST_CCFLAGS) test/tcc224.c -o tcc224
	$(CC) $(TEST_CCFLAGS) test/tcc225.c -o tcc225
	$(CC) $(TEST_CCFLAGS) test/tcc226.c -o tcc226
	$(CC) $(TEST_CCFLAGS) test/tcc227.c -o tcc227
	$(CC) $(TEST_CCFLAGS) test/tcc228.c -o tcc228
	$(CC) $(TEST_CCFLAGS) test/tcc229.c -o tcc229
	$(CC) $(TEST_CCFLAGS) test/tcw1.c -o tcw1
